### ISSUE TITLE
Blinds Don't Appear in Home App

### ISSUE THREAD

**Issue by simonpace** [jvmahon/homebridge-smartshades#5] opened 2020-08-23 07:19 UTC
Hi Jim,

I spoke to you via email a few weeks back - thank you for getting back to me.

I still can't seem to get my blinds to appear in the Home app. The plugin is installed and I've updated the config.json file and placed it in the homebridge folder.

I'm running homebridge on OSX.

I'm really keen to get this working so any assistance/suggestions you can provide would be greatly appreciated. I do understand if you are busy so this is obviously not urgent.

Thank you and regards
Simon

**Comment by simonpace** [comment] 2020-08-23 21:54
Please find attached the config.json file. I had to add .txt at the end of the file so it would be accepted. Thank you.
[config.json.txt](https://github.com/jvmahon/homebridge-smartshades/files/5115093/config.json.txt)

**Comment by simonpace** [comment] 2020-09-05 22:05
Hi Jim,

Just wanted to touch base on this to see if you got the config.json file ok.

thank you
Simon

**Comment by jvmahon** [comment] 2020-09-17 14:06
Sorry. I totally overlooked this. 

Change the "platform" in your config.json to "NEOShades" exactly like it is in the sample config.json and try again. Let me know if that works for you.

See: 
[config.json.txt](https://github.com/jvmahon/homebridge-smartshades/files/5239635/config.json.txt)

**Comment by jvmahon** [comment] 2020-10-14 00:08
As I didn't hear back from you, I assume the problem is solved so I'm closing the comment. Re-open if the problem persist.

**Closed by jvmahon** 2020-10-14 00:08 UTC
